# Generated by Django 5.2 on 2025-04-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_therapysession_ended_at_therapysession_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="recommendation_feedback",
            field=models.JSONField(default=dict),
        ),
    ]
